<?php
/**
 * This file is part of the Klarna Core module
 *
 * (c) Klarna Bank AB (publ)
 *
 * For the full copyright and license information, please view the NOTICE
 * and LICENSE files that were distributed with this source code.
 */
?>
<script type="text/javascript" id="klarna-credit-lib-x">
    /* <![CDATA[ */
    (function(w,d) {
        var url = 'https://x.klarnacdn.net/kp/lib/v1/api.js';
        n = d.createElement('script');
        c = d.getElementById('klarna-credit-lib-x');
        n.async = !0;
        n.src = url + '?' + (new Date()).getTime();
        c.parentNode.replaceChild(n, c);
    })(this,document);

    function fireWhenReady(method) {
        if (window.hasOwnProperty('Klarna')) {
            method();
        } else {
            setTimeout(function () {
                fireWhenReady(method);
            }, 100);
        }
    }

    // Used to register Klarna payment methods that need to call authorize on payment.save()
    var klarnaPaymentArray = [];
    /* ]]> */
</script>
