<?php
/**
 * This file is part of the Klarna Core module
 *
 * (c) Klarna Bank AB (publ)
 *
 * For the full copyright and license information, please view the NOTICE
 * and LICENSE files that were distributed with this source code.
 */

/**
 * @var Klarna_Payments_Block_Payments $this
 */
?>
<?php if (Mage::getStoreConfigFlag('payment/' . $this->getMethodCode() . '/active')) : ?>
<script type="text/javascript">
//<![CDATA[
    var usregions = <?php echo $this->getRegionsUS(); ?>;
//]]>
</script>
<?php endif; ?>